server:
  port: ${PORT:40100}
spring:
  application:
    name: xc-service-search
#  data:
#    elasticsearch:
#      cluster-name: xuecheng
#      cluster-nodes: 127.0.0.1:9300
xuecheng:
  elasticsearch:
    hostlist: ${eshostlist:127.0.0.1:9200} #多个结点中间用逗号分隔